export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/3/5/l/-original-imaghx9qmgqsk9s4.jpeg?q=70',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (Blue, 128 GB)',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 11",
      imgSrc: 'https://rukminim2.flixcart.com/image/312/312/k2jbyq80pkrrdj/mobile-refurbished/q/z/g/iphone-11-128-a-mwm32hn-a-apple-0-original-imafkg25hjmuy98e.jpeg?q=70',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 11 (Red, 64 GB)',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/tablet/v/6/4/-original-imagu2h3sfh3mhhb.jpeg?q=70',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab Yoga 11 4 GB RAM 128 GB ROM 11 inch with Wi-Fi+4G Tablet (Storm Grey)',
      price: '17,999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 13 (128GB) - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 Intel Core i5 ",
      imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/computer/p/x/x/-original-imahyyhqfquhkrvf.jpeg?q=70',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 13th Gen 13500H - (16 GB/512 GB SSD/Windows 11 Home) 16IRL8 Thin and Light Laptop ',
      price: '70,990',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/tablet/9/c/w/-original-imagu5gb2gzvduvz.jpeg?q=70',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'SAMSUNG Galaxy Tab A9+ 4 GB RAM 64 GB ROM 11.0 inch with Wi-Fi Only Tablet (Navy)',
      price: '18,999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/computer/m/b/n/-original-imagfdf4xnbyyxpa.jpeg?q=70',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },

   {
    id: 10,
    category: 'laptops',
    title: "ASUS Vivobook 15 Intel Core i3",
    imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/computer/j/t/b/-original-imagpxgqjeghkq7b.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'ASUS Vivobook 15 Intel Core i3 12th Gen 1215U - (16 GB/512 GB SSD/Windows 11 Home) X1502ZA-EJ993WS Thin and Light Laptop ',
    price: '37,990'
   },
   {
    id: 20,
    category: 'watches',
    title: "Apple Watch Series7",
    imgSrc: 'https://rukminim2.flixcart.com/image/612/612/ku8pbbk0/smartwatch/c/p/8/ios-mkj03hn-a-apple-yes-original-imag7eqyff4ryyuw.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Apple Watch Series7(GPS+Cellular, 41mm)-Gold Stainless Steel Case-Gold Milanese Loop  (Gold Strap, Regular)',
    price: '73,900'
   },
   {
    id: 11,
    category: 'laptops',
    title: "MSI Modern 14 Intel Core i3 12th Gen ",
    imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/computer/8/v/p/-original-imagvyw9dqmvqxmv.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'MSI Modern 14 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) Modern 14 C12M-445IN / Modern 14 C12MO-1022IN Thin and Light Laptop ',
    price: '29,990'
   },
   {
    id: 12,
    category: 'laptops',
    title: "HP Intel Core i5 12th Gen 1235U ",
    imgSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/computer/c/p/u/-original-imagykgpfe48frjw.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'HP Intel Core i5 12th Gen 1235U - (16 GB/512 GB SSD/Windows 11 Home) 15s-fq5330TU Thin and Light Laptop  (15.6 inch, Natural Silver, 1.69 Kg)',
    price: '29,990'
   },
   {
    id: 13,
    category: 'watches',
    title: "Apple Watch Series 8 ",
    imgSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/l/9/p/-original-imaghxg3ynvzcvkg.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Apple Watch Series 8, 45mm GPS + Cellular ECG app, Temperature sensor, Crash Detection  (Starlight Sport Strap, Regular)',
    price: '41,999'
   },
   {
    id: 14,
    category: 'watches',
    title: "Apple Watch Ultra 2",
    imgSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/5/b/i/-original-imagtcpckkwpvkn3.jpeg?q=70',
    amazonLink: 'https://amzn.to/3PuckZp',
    description: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium Case with Blue Ocean Band  (Blue Strap, Free Size)',
    price: '89,900'
   },
  ]